/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.6/samples
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
	`java-library`
	id("org.springframework.boot") version "3.2.3"
	id("io.spring.dependency-management") version "1.1.4"
}

group = "com.github.oliveiradd"
version = "1.0.0"

java {
	sourceCompatibility = JavaVersion.VERSION_21
}

repositories {
	mavenCentral()
}

dependencies {
	implementation("javax.servlet:servlet-api:2.5")
	implementation("org.springframework.boot:spring-boot-starter-web")
}

tasks.jar {
    manifest {
        attributes["Main-Class"] = "com.github.oliveiradd.IPCheck.IPCheck"
    }
}